version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: progressbridge-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: progressbridge-ai-service
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PORT=8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: progressbridge-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/progressbridge
      - JWT_SECRET=progressbridge_jwt_secret_key_sih2026
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - mongodb
      - ai-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: progressbridge-frontend
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  mongo_data:
